site_name: Bayesian Book of Beliefs
site_url: https://redratz55.github.io/BayesianBookOfBeliefs/

theme:
  name: material

plugins:
  - search
  - blog:
      blog_dir: . # Tells MkDocs the whole site is a blog
      post_dir: posts
      post_url_format: "{date}/{slug}"
      archive: true
      categories: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
